name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push image'
        required: false
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: patchman

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - name: Define build args
      run: |
        echo "VERSION=$(cat Dockerfile | grep 'ARG PATCHMAN_VERSION' | sed -r 's/.*="(.*)"/\1/')" >> $GITHUB_ENV

    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tags: |
            type=semver,pattern={{version}},value=${{ env.VERSION }},enable={{is_default_branch}}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.VERSION }},enable={{is_default_branch}}
            type=semver,pattern={{major}},value=${{ env.VERSION }},enable={{is_default_branch}}
            type=ref,event=pr

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        outputs: type=local,dest=/tmp/image.tar
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: patchman-image
        path: /tmp/image.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: patchman-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/patchman-image.tar
          docker image ls -a    

      - name: Docker Compose with Tests Action
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          down-flags: "--volumes"

  push:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.inputs.push == 'true'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: patchman-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/patchman-image.tar
          docker image ls -a

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
